### ISSUE TITLE
action= and edit links are broken

### ISSUE THREAD

**Issue by RhinosF1** [kulttuuri/DiscordNotifications#42]
Examples: 
Edit: https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil%26action=edit should be https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil?action=edit
Same for delete and history

And for diff it is https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil%26diff=prev%26oldid=1727827 instead of https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil?diff=prev&oldid=1727827

I can get a fix for edit, delete and history once I get to my laptop but diff is more confusing as it uses multiple parameters

**Comment by RhinosF1** [comment]
Scratch that

I think what *actually* works would be to parse the input URL to replace & etc. with their % equivalents rather than the URL it outputs to discord.

**Comment by RhinosF1** [comment]
This might mean using $title instead of $url in line 9-13 of the code

**Comment by The-Voidwalker** [comment]
Correction:
https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil%26action=edit should be https://allthetropes.org/w/index.php?title=Pay%20Evil%20Unto%20Evil&action=edit OR https://allthetropes.org/wiki/Pay%20Evil%20Unto%20Evil?action=edit

The basic issue is that it's escaping the & character. This is caused because **everything** is passed through the parseurl method.
